---

- name: create load balancer
  azure_rm_loadbalancer:
    resource_group: "{{ az_rg_name }}"
    name: "{{ az_lb_name }}"
    frontend_ip_configurations:
      - name: frontendipconf0
        public_ip_address: ansible-loadbalancer-public
    backend_address_pools:
      - name: backendaddrpool0
    probes:
      - name: prob0
        port: 80
    load_balancing_rules:
      - name: lbrbalancingrule0
        frontend_ip_configuration: frontendipconf0
        backend_address_pool: backendaddrpool0
        frontend_port: 80
        backend_port: 80
        probe: prob0
