---
- name: create resource group
  azure_rm_resourcegroup:
    name: "{{ az_rg_name }}"
    location: "{{ az_location }}"
  run_once: true

- name: create an availability set
  azure_rm_availabilityset:
    name: "{{ az_availibility_set }}"
    resource_group: "{{ az_rg_name }}"
  run_once: true
