---

- name: create public ip
  azure_rm_publicipaddress:
    resource_group: "{{ az_rg_name }}"
    allocation_method: Static
    name: "{{ az_vm_name }}-public"
  register: public_ip

- name: create vm nic
  azure_rm_networkinterface:
    resource_group: "{{ az_rg_name }}"
    name: "{{ az_vm_name }}-nic"
    virtual_network: "{{ az_network_name }}"
    subnet: "{{ az_network_name }}-subnet"
    security_group: "{{ az_secgroup_name }}"
    ip_configurations:
      - name: ipconfig1
        primary: True
        public_ip_address_name: "{{ az_vm_name }}-public"

- name: create vm
  azure_rm_virtualmachine:
    resource_group: "{{ az_rg_name }}"
    name: "{{ az_vm_name }}"
    vm_size: "{{ az_vm_size }}"
    admin_username: "{{ az_vm_admin_user }}"
    network_interfaces: "{{ az_vm_name }}-nic"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ az_vm_admin_user }}/.ssh/authorized_keys
        key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    image: "{{ instance_info[os] }}"

- debug:
    msg: "{{ public_ip.state.ip_address }}"

- name: wait for connection
  wait_for:
    host: "{{ public_ip.state.ip_address }}"
    port: "{{ port | default(22) }}"
    delay: 10
