---

- name: set facts for cluster members
  set_fact:
    primary_node: "{{ ansible_play_hosts[0] }}"
    secondary_node: "{{ ansible_play_hosts[1] }}"
  run_once: true

- name: add cluster members to /etc/hosts
  lineinfile:
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    path: /etc/hosts
  loop: "{{ ansible_play_hosts }}"

- name: install pcs
  yum:
    state: installed
    name: 
    - pcs
    - pacemaker
    - fence-agents-all

- name: set password for hacluster user
  user:
    name: "{{ pcs_user }}"
    password: "{{ pcs_passwd | password_hash('sha512') }}"

- name: start and enable pcsd
  service:
    name: pcsd
    state: started
    enabled: true

- name: auth nodes
  shell: pcs cluster auth {{ primary_node }} {{ secondary_node }} -u {{ pcs_user }} {{ pcs_passwd }}
  delegate_to: "{{ primary_node }}"

- name: auth nodes
  shell: pcs cluster setup --start --enable --name cluster1 {{ primary_node }} {{ secondary_node }} -u {{ pcs_user }} {{ pcs_passwd }}
  delegate_to: "{{ primary_node }}"
