---

- name: set facts for cluster members
  set_fact:
    primary_node: "{{ ansible_play_hosts[0] }}"
    secondary_node: "{{ ansible_play_hosts[1] }}"
  run_once: true

- name: add cluster members to /etc/hosts
  lineinfile:
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
    path: /etc/hosts
  loop: "{{ ansible_play_hosts }}"

- name: install pcs
  yum:
    state: installed
    name: 
    - pcs
    - pacemaker
    - fence-agents-all

- name: set password for hacluster user
  user:
    name: "{{ pcs_user }}"
    password: "{{ pcs_passwd | password_hash('sha512', mysalt) }}"

- name: start and enable pcsd
  service:
    name: pcsd
    state: started
    enabled: true

- name: enable firewall rules
  firewalld:
    service: high-availability
    state: enabled
    permanent: yes
    immediate: yes

- name: check if cluster configuration already exists
  stat:
    path: /var/lib/pacemaker/cib/cib.xml
  register: existing_cluster
  delegate_to: "{{ primary_node }}"

- name: auth nodes
  shell: pcs host auth {{ primary_node }} {{ secondary_node }} -u {{ pcs_user }} -p {{ pcs_passwd }}
  delegate_to: "{{ primary_node }}"
  no_log: false
  when: existing_cluster.stat.exists

- name: create cluster
  shell: pcs cluster setup --start --enable cluster1 {{ primary_node }} {{ secondary_node }}
  delegate_to: "{{ primary_node }}"
  when: existing_cluster.stat.exists
